### PR TITLE
My Blog Page

### PR DESCRIPTION
**Pull request by Rekha-Umashankar**

### CODE REVIEW

**Comment by emilyannemoses** [comment]
Merge this one too!

**Comment by Rekha-Umashankar** [comment]
> Merge this one too!

How do i resolve the above conflict?

**Comment by emilyannemoses** [comment]
I can help you out before class. I should be there by 5 and will be free to help until class starts at 630!

**Comment by Rekha-Umashankar** [comment]
> I can help you out before class. I should be there by 5 and will be free to help until class starts at 630!

Thanks, will see you little early before class.

**Pull request merged**
